jdbc:
  datasource:
    driver: com.mysql.cj.com.jus.jdbc.Driver
    url: com.jus.jdbc:mysql://localhost:3306/com.jus.jdbc?serverTimezone=GMT%2B8
    username: root
    password: 123456
  config:
    maxCount: 100
    debug: true
    aspectHandler: TestHandler